language: go
sudo: false
git:
  depth: 3

go:
  - "1.10"
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - dep ensure
#  - (cd example/github && dep ensure)

script:
#  - pwd
  - make test
  - (cd example/github && make install)
#  - pwd
#  - (cd example/github && icehubd db ping --db sqlite_local --verbose --logsrc)
#  - (cd example/github && icehubd db create --db sqlite_local --verbose --logsrc)
#  - (cd example/github && icehubd db migrate --db sqlite_local --verbose --logsrc)
  # TODO: we can test with mysql and postgres on travis, they are builtin service