language: go
sudo: false
git:
  depth: 3

go:
  - "1.10"
  - "1.11"
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - dep ensure
  - (cd example/github && dep ensure)

script:
  - make test
  - make test-cover
# FIXME: icehubd is broken because we no longer import gommon/config in ice ...
#  - (cd example/github && make install)
#  - (cd example/github && icehubd db ping --db sqlite_local --verbose --logSrc)
#  - (cd example/github && icehubd db create --db sqlite_local --verbose --logSrc)
#  - (cd example/github && icehubd db migrate --db sqlite_local --verbose --logSrc)
  # TODO: we can test with mysql and postgres on travis, they are builtin service

after_success:
  - bash <(curl -s https://codecov.io/bash)