language: go
sudo: false

go:
  - 1.9.x
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - dep ensure
  - cd example/github; dep ensure

script:
  - cd example/github && make install
  - cd example/github && icehubd db ping --db sqlite_local --verbose --logsrc