language: go
sudo: false
git:
  depth: 3

go:
  - 1.9.x
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - dep ensure
  - (cd example/github && dep ensure)
  - pwd

script:
  - pwd
  - make test
  - (cd example/github && make install)
  - pwd
  - (cd example/github && icehubd db ping --db sqlite_local --verbose --logsrc)
  # TODO: we can test with mysql and postgres on travis, they are builtin service